services:
  backend-db.prod:
    image: postgres:alpine
    volumes:
      - postgres:/data/postgres
    env_file:
      - .backend-db.ecopath.production.env
    networks:
      - ecopath-prod
    restart: unless-stopped

  backend.prod:
    image: ecopath-backend
    env_file: .backend.ecopath.production.env
    ports:
      - 8000:8000
    networks:
      - ecopath-prod
    restart: unless-stopped
    depends_on:
      - backend-db.prod

networks:
  ecopath-prod:
    ipam: 
      config: 
        - subnet: 10.1.0.0/16

volumes:
  postgres: